#include <wax/containers/vector.h>

#include <nectar/hive/hive_writer.h>

namespace nectar
{
    namespace
    {
        void WriteValue(const HiveValue& value, wax::String& out) {
            switch (value.m_type)
            {
                case HiveValue::Type::STRING:
                    out.Append('"');
                    // Escape special characters
                    for (size_t i = 0; i < value.m_str.Size(); ++i)
                    {
                        char c = value.m_str[i];
                        switch (c)
                        {
                            case '"':
                                out.Append("\\\"", 2);
                                break;
                            case '\\':
                                out.Append("\\\\", 2);
                                break;
                            case '\n':
                                out.Append("\\n", 2);
                                break;
                            case '\t':
                                out.Append("\\t", 2);
                                break;
                            default:
                                out.Append(c);
                                break;
                        }
                    }
                    out.Append('"');
                    break;

                case HiveValue::Type::BOOL:
                    out.Append(value.m_boolVal ? "true" : "false");
                    break;

                case HiveValue::Type::INT: {
                    char buf[32];
                    int len = std::snprintf(buf, sizeof(buf), "%lld", static_cast<long long>(value.m_intVal));
                    out.Append(buf, static_cast<size_t>(len));
                    break;
                }

                case HiveValue::Type::FLOAT: {
                    char buf[64];
                    int len = std::snprintf(buf, sizeof(buf), "%g", value.m_floatVal);
                    out.Append(buf, static_cast<size_t>(len));
                    break;
                }

                case HiveValue::Type::STRING_ARRAY:
                    out.Append('[');
                    for (size_t i = 0; i < value.m_array.Size(); ++i)
                    {
                        if (i > 0)
                            out.Append(", ", 2);
                        out.Append('"');
                        for (size_t j = 0; j < value.m_array[i].Size(); ++j)
                        {
                            char c = value.m_array[i][j];
                            switch (c)
                            {
                                case '"':
                                    out.Append("\\\"", 2);
                                    break;
                                case '\\':
                                    out.Append("\\\\", 2);
                                    break;
                                default:
                                    out.Append(c);
                                    break;
                            }
                        }
                        out.Append('"');
                    }
                    out.Append(']');
                    break;
            }
        }
    } // namespace

    wax::String HiveWriter::Write(const HiveDocument& doc, comb::DefaultAllocator& alloc) {
        wax::String out{alloc};
        out.Append("# Auto-generated by Nectar\n");

        // Collect and sort section names for deterministic output
        wax::Vector<wax::StringView> sectionNames{alloc};
        for (auto it = doc.Sections().Begin(); it != doc.Sections().End(); ++it)
        {
            sectionNames.PushBack(it.Key().View());
        }

        // Simple insertion sort (small number of sections)
        for (size_t i = 1; i < sectionNames.Size(); ++i)
        {
            auto key = sectionNames[i];
            size_t j = i;
            while (j > 0 && sectionNames[j - 1].Compare(key) > 0)
            {
                sectionNames[j] = sectionNames[j - 1];
                --j;
            }
            sectionNames[j] = key;
        }

        for (size_t s = 0; s < sectionNames.Size(); ++s)
        {
            if (s > 0 || out.Size() > 0)
                out.Append('\n');

            out.Append('[');
            out.Append(sectionNames[s].Data(), sectionNames[s].Size());
            out.Append("]\n", 2);

            // Find the section
            wax::String secKey{alloc, sectionNames[s]};
            auto* section = doc.Sections().Find(secKey);
            if (!section)
                continue;

            // Collect and sort keys for deterministic output
            wax::Vector<wax::StringView> keys{alloc};
            for (auto it = section->Begin(); it != section->End(); ++it)
            {
                keys.PushBack(it.Key().View());
            }

            for (size_t i = 1; i < keys.Size(); ++i)
            {
                auto key = keys[i];
                size_t j = i;
                while (j > 0 && keys[j - 1].Compare(key) > 0)
                {
                    keys[j] = keys[j - 1];
                    --j;
                }
                keys[j] = key;
            }

            for (size_t k = 0; k < keys.Size(); ++k)
            {
                out.Append(keys[k].Data(), keys[k].Size());
                out.Append(" = ", 3);

                wax::String valKey{alloc, keys[k]};
                auto* value = section->Find(valKey);
                if (value)
                {
                    WriteValue(*value, out);
                }
                out.Append('\n');
            }
        }

        return out;
    }
} // namespace nectar
