#include <forge/material_inspector.h>

#include <forge/editor_undo.h>

#include <QCheckBox>
#include <QColorDialog>
#include <QComboBox>
#include <QDoubleSpinBox>
#include <QFile>
#include <QFileDialog>
#include <QHBoxLayout>
#include <QLabel>
#include <QPushButton>
#include <QTextStream>
#include <QVBoxLayout>

#include <filesystem>

namespace forge
{
    MatFields ParseMatFile(const std::filesystem::path& path)
    {
        MatFields mat;
        QFile file{QString::fromStdString(path.string())};
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
            return mat;

        QString section;
        while (!file.atEnd())
        {
            QString line = file.readLine().trimmed();
            if (line.isEmpty() || line.startsWith('#'))
                continue;
            if (line.startsWith('[') && line.endsWith(']'))
            {
                section = line.mid(1, line.size() - 2);
                continue;
            }
            int eq = line.indexOf('=');
            if (eq < 0)
                continue;

            QString key = line.left(eq).trimmed();
            QString val = line.mid(eq + 1).trimmed();
            if (val.startsWith('"') && val.endsWith('"'))
                val = val.mid(1, val.size() - 2);

            if (section == "material")
            {
                if (key == "name")
                    mat.name = val;
                else if (key == "shader")
                    mat.shader = val;
                else if (key == "blend")
                    mat.blend = val;
                else if (key == "double_sided")
                    mat.doubleSided = (val == "true");
                else if (key == "alpha_cutoff")
                    mat.alphaCutoff = val.toFloat();
            }
            else if (section == "factors")
            {
                if (key == "base_color")
                {
                    auto parts = val.split(' ');
                    for (int i = 0; i < 4 && i < parts.size(); ++i)
                        mat.baseColor[i] = parts[i].toFloat();
                }
                else if (key == "metallic")
                    mat.metallic = val.toFloat();
                else if (key == "roughness")
                    mat.roughness = val.toFloat();
            }
            else if (section == "textures")
            {
                mat.textures[key] = val;
            }
        }
        return mat;
    }

    void WriteMatFile(const std::filesystem::path& path, const MatFields& mat)
    {
        QFile file{QString::fromStdString(path.string())};
        if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
            return;

        QTextStream out{&file};
        out << "# Auto-generated by Nectar\n\n";
        out << "[factors]\n";
        out << QString{"base_color = \"%1 %2 %3 %4\"\n"}
                   .arg(mat.baseColor[0]).arg(mat.baseColor[1])
                   .arg(mat.baseColor[2]).arg(mat.baseColor[3]);
        out << QString{"metallic = %1\n"}.arg(mat.metallic);
        out << QString{"roughness = %1\n"}.arg(mat.roughness);
        out << "\n[material]\n";
        out << QString{"alpha_cutoff = %1\n"}.arg(mat.alphaCutoff);
        out << QString{"blend = \"%1\"\n"}.arg(mat.blend);
        out << QString{"double_sided = %1\n"}.arg(mat.doubleSided ? "true" : "false");
        out << QString{"name = \"%1\"\n"}.arg(mat.name);
        out << QString{"shader = \"%1\"\n"}.arg(mat.shader);
        if (!mat.textures.empty())
        {
            out << "\n[textures]\n";
            for (auto it = mat.textures.begin(); it != mat.textures.end(); ++it)
            {
                out << QString{"%1 = \"%2\"\n"}.arg(it->first, it->second);
            }
        }
    }

    struct GuidEntry
    {
        QString name;
        QString fullPath;
    };

    static std::map<QString, GuidEntry> BuildGuidToPathMap(const std::filesystem::path& assetsRoot)
    {
        std::map<QString, GuidEntry> guidMap;
        if (!std::filesystem::exists(assetsRoot))
            return guidMap;

        std::error_code ec;
        for (auto it = std::filesystem::recursive_directory_iterator{assetsRoot, ec};
             it != std::filesystem::recursive_directory_iterator{}; ++it)
        {
            if (!it->is_regular_file())
                continue;
            if (it->path().extension().string() != ".hiveid")
                continue;

            QFile f{QString::fromStdString(it->path().string())};
            if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
                continue;

            while (!f.atEnd())
            {
                QString line = f.readLine().trimmed();
                if (line.startsWith("guid="))
                {
                    QString guid = line.mid(5);
                    auto assetFile = it->path().parent_path() / it->path().stem();
                    GuidEntry entry;
                    entry.name = QString::fromStdString(assetFile.filename().string());
                    entry.fullPath = QString::fromStdString(assetFile.string());
                    guidMap["{" + guid + "}"] = entry;
                    break;
                }
            }
        }
        return guidMap;
    }

    static QString ReadGuidFromHiveId(const std::filesystem::path& assetPath)
    {
        auto hiveidPath = std::filesystem::path{assetPath}.concat(".hiveid");
        std::error_code ec;
        if (!std::filesystem::exists(hiveidPath, ec))
            return {};
        QFile hf{QString::fromStdString(hiveidPath.string())};
        if (!hf.open(QIODevice::ReadOnly | QIODevice::Text))
            return {};
        while (!hf.atEnd())
        {
            QString line = hf.readLine().trimmed();
            if (line.startsWith("guid="))
                return "{" + line.mid(5) + "}";
        }
        return {};
    }

    MaterialInspector::MaterialInspector(const std::filesystem::path& path, EditorUndoManager& editorUndo,
                                         QWidget* parent)
        : QWidget{parent}
    {
        auto* rootLayout = new QVBoxLayout{this};
        rootLayout->setContentsMargins(0, 0, 0, 0);
        rootLayout->setSpacing(4);

        QString originalContent;
        {
            QFile origFile{QString::fromStdString(path.string())};
            if (origFile.open(QIODevice::ReadOnly | QIODevice::Text))
                originalContent = origFile.readAll();
        }

        auto mat = ParseMatFile(path);
        auto capturedPath = std::make_shared<std::filesystem::path>(path);
        auto matState = std::make_shared<MatFields>(mat);

        auto saveMat = [capturedPath, matState, &editorUndo] {
            auto beforeContent = std::make_shared<QString>();
            {
                QFile f{QString::fromStdString(capturedPath->string())};
                if (f.open(QIODevice::ReadOnly | QIODevice::Text))
                    *beforeContent = f.readAll();
            }

            WriteMatFile(*capturedPath, *matState);

            auto afterState = std::make_shared<MatFields>(*matState);
            editorUndo.Push(
                [capturedPath, beforeContent] {
                    QFile f{QString::fromStdString(capturedPath->string())};
                    if (f.open(QIODevice::WriteOnly | QIODevice::Text))
                        f.write(beforeContent->toUtf8());
                },
                [capturedPath, afterState] {
                    WriteMatFile(*capturedPath, *afterState);
                });
        };

        auto addRow = [rootLayout](const char* label, const QString& value) {
            auto* row = new QWidget;
            auto* hbox = new QHBoxLayout{row};
            hbox->setContentsMargins(4, 0, 4, 0);
            hbox->setSpacing(8);
            auto* lbl = new QLabel{label};
            lbl->setStyleSheet("color: #888; font-size: 12px;");
            lbl->setFixedWidth(70);
            hbox->addWidget(lbl);
            auto* val = new QLabel{value};
            val->setStyleSheet("color: #e8e8e8; font-size: 12px;");
            val->setTextInteractionFlags(Qt::TextSelectableByMouse);
            val->setWordWrap(true);
            hbox->addWidget(val, 1);
            rootLayout->addWidget(row);
        };

        addRow("Shader", mat.shader);

        auto* blendCombo = new QComboBox;
        blendCombo->addItems({"opaque", "alpha_test", "alpha_blend"});
        int blendIdx = blendCombo->findText(mat.blend);
        if (blendIdx >= 0)
            blendCombo->setCurrentIndex(blendIdx);
        connect(blendCombo, &QComboBox::currentTextChanged, this, [matState, saveMat, this](const QString& text) {
            matState->blend = text;
            saveMat();
            emit materialModified();
        });

        auto* blendRow = new QWidget;
        auto* blendLayout = new QHBoxLayout{blendRow};
        blendLayout->setContentsMargins(4, 0, 4, 0);
        blendLayout->setSpacing(8);
        auto* blendLabel = new QLabel{"Blend"};
        blendLabel->setStyleSheet("color: #888; font-size: 12px;");
        blendLabel->setFixedWidth(70);
        blendLayout->addWidget(blendLabel);
        blendLayout->addWidget(blendCombo, 1);
        rootLayout->addWidget(blendRow);

        auto* dsCheck = new QCheckBox{"Double Sided"};
        dsCheck->setChecked(mat.doubleSided);
        dsCheck->setStyleSheet("color: #e8e8e8; font-size: 12px; margin-left: 78px;");
        connect(dsCheck, &QCheckBox::toggled, this, [matState, saveMat, this](bool checked) {
            matState->doubleSided = checked;
            saveMat();
            emit materialModified();
        });
        rootLayout->addWidget(dsCheck);

        auto addSlider = [&](const char* label, float value, float min, float max,
                             std::function<void(float)> onChange) {
            auto* row = new QWidget;
            auto* hbox = new QHBoxLayout{row};
            hbox->setContentsMargins(4, 0, 4, 0);
            hbox->setSpacing(8);
            auto* lbl = new QLabel{label};
            lbl->setStyleSheet("color: #888; font-size: 12px;");
            lbl->setFixedWidth(70);
            hbox->addWidget(lbl);

            auto* spin = new QDoubleSpinBox;
            spin->setRange(min, max);
            spin->setSingleStep(0.01);
            spin->setDecimals(3);
            spin->setValue(value);
            connect(spin, &QDoubleSpinBox::editingFinished, this, [spin, onChange, saveMat, this] {
                onChange(static_cast<float>(spin->value()));
                saveMat();
                emit materialModified();
            });
            hbox->addWidget(spin, 1);
            rootLayout->addWidget(row);
        };

        addSlider("Metallic", mat.metallic, 0.f, 1.f, [matState](float v) { matState->metallic = v; });
        addSlider("Roughness", mat.roughness, 0.f, 1.f, [matState](float v) { matState->roughness = v; });
        addSlider("Alpha Cut", mat.alphaCutoff, 0.f, 1.f, [matState](float v) { matState->alphaCutoff = v; });

        QColor currentColor = QColor::fromRgbF(mat.baseColor[0], mat.baseColor[1], mat.baseColor[2], mat.baseColor[3]);
        auto* colorBtn = new QPushButton;
        colorBtn->setFixedHeight(24);
        colorBtn->setStyleSheet(
            QString{"background: %1; border: 1px solid #2a2a2a; border-radius: 3px;"}.arg(currentColor.name()));

        auto* colorRow = new QWidget;
        auto* colorLayout = new QHBoxLayout{colorRow};
        colorLayout->setContentsMargins(4, 0, 4, 0);
        colorLayout->setSpacing(8);
        auto* colorLabel = new QLabel{"Base Color"};
        colorLabel->setStyleSheet("color: #888; font-size: 12px;");
        colorLabel->setFixedWidth(70);
        colorLayout->addWidget(colorLabel);
        colorLayout->addWidget(colorBtn, 1);
        rootLayout->addWidget(colorRow);

        connect(colorBtn, &QPushButton::clicked, this, [this, colorBtn, matState, saveMat, currentColor] {
            QColor color = QColorDialog::getColor(currentColor, this, "Base Color");
            if (color.isValid())
            {
                matState->baseColor[0] = static_cast<float>(color.redF());
                matState->baseColor[1] = static_cast<float>(color.greenF());
                matState->baseColor[2] = static_cast<float>(color.blueF());
                matState->baseColor[3] = 1.f;
                colorBtn->setStyleSheet(
                    QString{"background: %1; border: 1px solid #2a2a2a; border-radius: 3px;"}.arg(color.name()));
                saveMat();
                emit materialModified();
            }
        });

        auto assetsRoot = path.parent_path();
        auto guidMap = BuildGuidToPathMap(assetsRoot);

        if (!mat.textures.empty())
        {
            auto* texHeader = new QLabel{"Textures"};
            texHeader->setStyleSheet("color: #f0a500; font-size: 12px; font-weight: bold; margin-top: 8px;");
            texHeader->setContentsMargins(4, 0, 0, 0);
            rootLayout->addWidget(texHeader);
        }

        for (const auto& [texKey, texGuid] : mat.textures)
        {
            auto* row = new QWidget;
            auto* vbox = new QVBoxLayout{row};
            vbox->setContentsMargins(4, 4, 4, 4);
            vbox->setSpacing(4);

            auto* headerRow = new QWidget;
            auto* headerLayout = new QHBoxLayout{headerRow};
            headerLayout->setContentsMargins(0, 0, 0, 0);
            headerLayout->setSpacing(4);

            auto* lbl = new QLabel{texKey};
            lbl->setStyleSheet("color: #999; font-size: 11px; font-weight: bold;");
            headerLayout->addWidget(lbl);
            headerLayout->addStretch();

            QString capturedKey = texKey;
            auto capturedAssetsRoot = std::make_shared<std::filesystem::path>(assetsRoot);

            auto* searchBtn = new QPushButton{"\xf0\x9f\x94\x8d"};
            searchBtn->setFixedSize(22, 22);
            searchBtn->setCursor(Qt::PointingHandCursor);
            searchBtn->setToolTip("Select texture");
            searchBtn->setStyleSheet(
                "QPushButton { background: #222; color: #ccc; border: 1px solid #333;"
                "  border-radius: 3px; font-size: 12px; }"
                "QPushButton:hover { border-color: #f0a500; color: #f0a500; }");
            connect(searchBtn, &QPushButton::clicked, this,
                    [matState, saveMat, capturedKey, capturedAssetsRoot, this] {
                        QString file = QFileDialog::getOpenFileName(
                            this, "Select Texture",
                            QString::fromStdString(capturedAssetsRoot->string()),
                            "Textures (*.png *.jpg *.jpeg *.tga *.bmp *.hdr)");
                        if (file.isEmpty())
                            return;

                        auto guid = ReadGuidFromHiveId(std::filesystem::path{file.toStdString()});
                        if (!guid.isEmpty())
                        {
                            matState->textures[capturedKey] = guid;
                            saveMat();
                            emit materialModified();
                        }
                    });
            headerLayout->addWidget(searchBtn);

            auto* clearBtn = new QPushButton{"\xc3\x97"};
            clearBtn->setFixedSize(22, 22);
            clearBtn->setCursor(Qt::PointingHandCursor);
            clearBtn->setToolTip("Clear texture");
            clearBtn->setStyleSheet(
                "QPushButton { background: #222; color: #666; border: 1px solid #333;"
                "  border-radius: 3px; font-size: 14px; }"
                "QPushButton:hover { border-color: #ef5350; color: #ef5350; }");
            connect(clearBtn, &QPushButton::clicked, this, [matState, saveMat, capturedKey, this] {
                matState->textures[capturedKey] = "";
                saveMat();
                emit materialModified();
            });
            headerLayout->addWidget(clearBtn);

            vbox->addWidget(headerRow);

            auto guidIt = guidMap.find(texGuid);
            if (guidIt != guidMap.end())
            {
                auto* contentRow = new QWidget;
                auto* contentLayout = new QHBoxLayout{contentRow};
                contentLayout->setContentsMargins(0, 0, 0, 0);
                contentLayout->setSpacing(8);

                QImage img;
                if (img.load(guidIt->second.fullPath))
                {
                    auto* thumb = new QLabel;
                    QPixmap pix = QPixmap::fromImage(img.scaled(48, 48, Qt::KeepAspectRatio, Qt::SmoothTransformation));
                    thumb->setPixmap(pix);
                    thumb->setFixedSize(48, 48);
                    thumb->setStyleSheet("border: 1px solid #2a2a2a; border-radius: 3px; background: #1a1a1a;");
                    contentLayout->addWidget(thumb);
                }

                auto* nameLabel = new QLabel{guidIt->second.name};
                nameLabel->setStyleSheet("color: #e8e8e8; font-size: 11px;");
                nameLabel->setWordWrap(true);
                contentLayout->addWidget(nameLabel, 1);

                vbox->addWidget(contentRow);
            }
            else if (!texGuid.isEmpty())
            {
                auto* emptyLabel = new QLabel{"None"};
                emptyLabel->setStyleSheet("color: #555; font-size: 10px; font-style: italic;");
                vbox->addWidget(emptyLabel);
            }

            row->setStyleSheet("QWidget { background: #161616; border-radius: 4px; }");
            rootLayout->addWidget(row);
        }
    }
} // namespace forge
