#include <waggle/project/cmake_generator.h>

#include <wax/containers/string.h>

#include <fstream>

namespace waggle
{
    namespace
    {
        wax::String NormalizePath(wax::StringView path, comb::DefaultAllocator& alloc)
        {
            wax::String normalized{alloc, path};
            char* data = normalized.Data();
            for (size_t i = 0; i < normalized.Size(); ++i)
            {
                if (data[i] == '\\')
                {
                    data[i] = '/';
                }
            }
            return normalized;
        }
    } // namespace

    wax::String CMakeGenerator::Generate(const CMakeGenConfig& config, comb::DefaultAllocator& alloc)
    {
        wax::String out{alloc};
        out.Reserve(3072);
        const wax::String enginePath = NormalizePath(config.m_enginePath, alloc);

        out.Append("# Generated by HiveEngine\n");
        out.Append("cmake_minimum_required(VERSION 3.28)\n");
        out.Append("if(WIN32)\n");
        out.Append("    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)\n");
        out.Append("endif()\n\n");
        out.Append("if(WIN32 AND NOT CMAKE_RC_COMPILER)\n");
        out.Append("    file(GLOB RC_PATHS\n");
        out.Append("        \"C:/Program Files (x86)/Windows Kits/10/bin/*/x64/rc.exe\"\n");
        out.Append("        \"C:/Program Files (x86)/Windows Kits/*/bin/x64/rc.exe\"\n");
        out.Append("    )\n");
        out.Append("    if(RC_PATHS)\n");
        out.Append("        list(GET RC_PATHS 0 FOUND_RC)\n");
        out.Append("        set(CMAKE_RC_COMPILER \"${FOUND_RC}\" CACHE FILEPATH \"RC Compiler\")\n");
        out.Append("    else()\n");
        out.Append("        set(CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC Compiler\")\n");
        out.Append("    endif()\n");
        out.Append("endif()\n\n");
        out.Append("project(");
        out.Append(config.m_projectName);
        out.Append(" LANGUAGES CXX)\n\n");

        out.Append("set(CMAKE_CXX_STANDARD 20)\n");
        out.Append("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n");
        out.Append("set(CMAKE_CXX_EXTENSIONS OFF)\n\n");

        out.Append("if(NOT HIVE_ENGINE_DIR)\n");
        out.Append("    set(HIVE_ENGINE_DIR \"$ENV{HIVE_ENGINE_DIR}\" CACHE PATH \"Path to HiveEngine\")\n");
        out.Append("endif()\n");
        out.Append("if(NOT HIVE_ENGINE_DIR)\n");
        out.Append("    set(HIVE_ENGINE_DIR \"");
        out.Append(enginePath.View());
        out.Append("\" CACHE PATH \"Path to HiveEngine\")\n");
        out.Append("endif()\n\n");

        out.Append("set(HIVE_BUILD_EMBEDDED_PROJECTS OFF CACHE BOOL \"Build bundled sample projects\" FORCE)\n");
        out.Append("add_subdirectory(${HIVE_ENGINE_DIR} ${CMAKE_BINARY_DIR}/engine EXCLUDE_FROM_ALL)\n\n");
        out.Append("include(${HIVE_ENGINE_DIR}/cmake/HiveProject.cmake)\n\n");

        out.Append("file(GLOB_RECURSE GAMEPLAY_SOURCES CONFIGURE_DEPENDS src/*.cpp src/*.h)\n\n");
        out.Append("hive_add_game_project(\n");
        out.Append("    TARGET gameplay\n");
        out.Append("    PROJECT_ROOT \"${CMAKE_CURRENT_SOURCE_DIR}\"\n");
        out.Append("    SOURCES ${GAMEPLAY_SOURCES}\n");
        if (config.m_linkSwarm)
        {
            out.Append("    LINK_SWARM\n");
        }
        if (config.m_linkTerra)
        {
            out.Append("    LINK_TERRA\n");
        }
        if (config.m_linkAntennae)
        {
            out.Append("    LINK_ANTENNAE\n");
        }
        out.Append(")\n\n");

        out.Append("if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/assets/shaders)\n");
        out.Append("    include(${HIVE_ENGINE_DIR}/cmake/CompileShaders.cmake)\n");
        out.Append("endif()\n");

        return out;
    }

    bool CMakeGenerator::WriteToProject(const CMakeGenConfig& config, comb::DefaultAllocator& alloc)
    {
        auto content = Generate(config, alloc);

        wax::String path{config.m_projectRoot};
        path.Append("/CMakeLists.txt");

        std::ofstream file{path.CStr()};
        if (!file)
            return false;

        file.write(content.CStr(), static_cast<std::streamsize>(content.Size()));
        return file.good();
    }

} // namespace waggle
