#include <waggle/project/cmake_generator.h>

#include <fstream>
#include <string>

namespace waggle
{

wax::String<> CMakeGenerator::Generate(const CMakeGenConfig& config,
                                       comb::DefaultAllocator& alloc)
{
    wax::String<> out{alloc};
    out.Reserve(2048);

    out.Append("# Generated by HiveEngine\n");
    out.Append("cmake_minimum_required(VERSION 3.28)\n");
    out.Append("project(");
    out.Append(config.project_name);
    out.Append(" LANGUAGES CXX)\n\n");

    out.Append("set(CMAKE_CXX_STANDARD 20)\n");
    out.Append("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n");
    out.Append("set(CMAKE_CXX_EXTENSIONS OFF)\n\n");

    out.Append("if(NOT HIVE_ENGINE_DIR)\n");
    out.Append("    set(HIVE_ENGINE_DIR \"$ENV{HIVE_ENGINE_DIR}\" CACHE PATH \"Path to HiveEngine\")\n");
    out.Append("endif()\n");
    out.Append("if(NOT HIVE_ENGINE_DIR)\n");
    out.Append("    set(HIVE_ENGINE_DIR \"");
    out.Append(config.engine_path);
    out.Append("\" CACHE PATH \"Path to HiveEngine\")\n");
    out.Append("endif()\n\n");

    out.Append("add_subdirectory(${HIVE_ENGINE_DIR} ${CMAKE_BINARY_DIR}/engine EXCLUDE_FROM_ALL)\n\n");

    out.Append("file(GLOB_RECURSE GAMEPLAY_SOURCES src/*.cpp src/*.h)\n\n");

    out.Append("if(GAMEPLAY_SOURCES)\n");
    out.Append("    add_library(gameplay MODULE ${GAMEPLAY_SOURCES})\n");
    out.Append("    target_link_libraries(gameplay PRIVATE Queen Waggle Hive Comb Wax Nectar");
    if (config.link_swarm)
        out.Append(" Swarm");
    if (config.link_terra)
        out.Append(" Terra");
    if (config.link_antennae)
        out.Append(" Antennae");
    out.Append(")\n");
    out.Append("    target_include_directories(gameplay PRIVATE src)\n");
    out.Append("    set_target_properties(gameplay PROPERTIES PREFIX \"\" OUTPUT_NAME \"gameplay\")\n");
    out.Append("endif()\n\n");

    out.Append("if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/assets/shaders)\n");
    out.Append("    include(${HIVE_ENGINE_DIR}/cmake/CompileShaders.cmake)\n");
    out.Append("endif()\n");

    return out;
}

bool CMakeGenerator::WriteToProject(const CMakeGenConfig& config,
                                    comb::DefaultAllocator& alloc)
{
    auto content = Generate(config, alloc);

    std::string path;
    path.append(config.project_root.Data(), config.project_root.Size());
    path += "/CMakeLists.txt";

    std::ofstream file{path};
    if (!file)
        return false;

    file.write(content.CStr(), static_cast<std::streamsize>(content.Size()));
    return file.good();
}

} // namespace waggle
